spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/starter
    username: root
    password: 99758049

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: false
        use_sql_comments: false
        jdbc:
          time_zone: UTC

  security:
    token-secret: ${JWT_SECRET:my-secret-key}